### ISSUE TITLE
mc won't start without internet connection

### ISSUE THREAD

**Issue by szopin** [sailfishos-chum/mc#2]
Just noticed that starting mc requires for some unknown reason internet connection.
Steps to reproduce:
1. start terminal
2. turn airplane mode on
3. run 'mc'

Expected result:
mc running

Actual result:
Nothing happens until airplane mode is turned off, then mc appears (it actually does start but after about 2 minutes)

**Comment by szopin** [comment]
Looks like non-sfos issue https://midnight-commander.org/ticket/40
Maybe fixed in https://github.com/MidnightCommander/mc/commit/6f676d06676cc5d271583754f15473af78a36ac4 so 4.8.29 has a chance to have it

**Comment by MPolleke** [comment]
Hello Szopin,
Thank you. 
I can confirm that it does work correctly on 4.8.29. It is just that I don't support mc myself on chum. I prefer to not be release manager of a git repo with submodules. 

I do maintain it on Openrepos, where it is on 4.8.29:
https://openrepos.net/content/polleke/midnight-commander

**Comment by rinigus** [comment]
I updated mc at Chum to 4.8.29. Closing over here - please reopen if the issue persists.
